PROGRAM NEWTON
    IMPLICIT NONE
    CHARACTER(LEN=12):: INPUT
    REAL:: VALUE
    CALL GETARG(1, INPUT)
    READ(INPUT, *) VALUE
    PRINT *, VALUE

    CONTAINS
    FUNCTION GET_SQRT(INPUT, TOLERANCE) RESULT(P)
        REAL, INTENT(IN):: INPUT, TOLERANCE
        REAL:: P, DERIVATIVE

    END FUNCTION GET_SQRT

END PROGRAM NEWTON